spring.application.name=challenge-literatura

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/literatura_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# equivalent to prisma db push
spring.jpa.hibernate.ddl-auto=update
# if for show sql queries in console (debugging)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
# use specific sql dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

